create table actors (id bigint not null, name varchar(255), primary key (id));
create table content_type (id bigint not null, name varchar(255), tag varchar(255), primary key (id));
create table contents (id bigint not null, added TIMESTAMP, cover varchar(255), premier integer, production varchar(255), resource_path varchar(255), synopsis varchar(255), title varchar(255), feature_id bigint, type_id bigint, primary key (id));
create table contents_actors (content_id bigint not null, actor_id bigint not null);
create table contents_directors (content_id bigint not null, director_id bigint not null);
create table contents_genres (content_id bigint not null, genre_id bigint not null);
create table directors (id bigint not null, name varchar(255), primary key (id));
create table features (id bigint not null, name varchar(255), tag varchar(255), primary key (id));
create table genres (id bigint not null, name varchar(255), primary key (id));
create table history (id bigint not null, view_date TIMESTAMP, content_id bigint, user_id bigint, primary key (id));
create table plans (id bigint not null, description varchar(255), duration integer, name varchar(255), price double, primary key (id));
create table plans_features (plan_id bigint not null, feature_id bigint not null);
create table play_lists (content_id bigint not null, user_id bigint not null, added_date TIMESTAMP, primary key (content_id, user_id));
create table ratings (content_id bigint not null, user_id bigint not null, rating_date TIMESTAMP, rating integer, primary key (content_id, user_id));
create table role (id bigint not null, name varchar(255), tag varchar(255), primary key (id));
create table subscriptions (id bigint not null, finish TIMESTAMP, start TIMESTAMP, plan_id bigint, user_id bigint, primary key (id));
create table users (id bigint not null, address varchar(255), city varchar(255), country varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), postal_code varchar(255), province varchar(255), role_id bigint, primary key (id));
create table users_actors (user_id bigint not null, actor_id bigint not null);
create table users_directors (user_id bigint not null, director_id bigint not null);
create table users_genres (user_id bigint not null, genre_id bigint not null);
alter table content_type add constraint UK_835k6p59oajhwv7t0iotr99go unique (name);
alter table plans add constraint UK_j2syv9y60858xbq169nbeg7ea unique (name);
alter table role add constraint UK_8sewwnpamngi6b1dwaa88askk unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table contents add constraint FKncncwvyqor7a9tmr1oe3djrse foreign key (feature_id) references features;
alter table contents add constraint FK5yje6749x64cxwfnq4os2uwaw foreign key (type_id) references content_type;
alter table contents_actors add constraint FKaj4hrc32pqmm7e162xdmqcpp5 foreign key (actor_id) references actors;
alter table contents_actors add constraint FKmtin7jhpja8hcejl2brpq7o89 foreign key (content_id) references contents;
alter table contents_directors add constraint FK2l3ipcfbt6nawphxugcpeybv foreign key (director_id) references directors;
alter table contents_directors add constraint FKl8wr5gw7f07s9aj24ka3uonun foreign key (content_id) references contents;
alter table contents_genres add constraint FK7p1dhkd9p7ca33fydentusfvh foreign key (genre_id) references genres;
alter table contents_genres add constraint FKifd7ob4jyb0jv1ifppt8ka1ev foreign key (content_id) references contents;
alter table history add constraint FKq9ku17sjt5qh9nwyb2tijf1ui foreign key (content_id) references contents on delete cascade;
alter table history add constraint FKq4kh99ws9lhtls5i3o73gw30t foreign key (user_id) references users on delete cascade;
alter table plans_features add constraint FKa902akiy4m8vgr6xpqw95cnt8 foreign key (feature_id) references features;
alter table plans_features add constraint FKety512kqx53dlfvbwtl1w2ea6 foreign key (plan_id) references plans;
alter table play_lists add constraint FKavf17fr1aj2rwfgp3baqmkrov foreign key (content_id) references contents on delete cascade;
alter table play_lists add constraint FKhymlwlnfjcw5rr8wx97nxy98m foreign key (user_id) references users on delete cascade;
alter table ratings add constraint FKq83y9alleiocjmbiu6o82nd7l foreign key (content_id) references contents on delete cascade;
alter table ratings add constraint FKb3354ee2xxvdrbyq9f42jdayd foreign key (user_id) references users on delete cascade;
alter table subscriptions add constraint FKb1uf5qnxi6uj95se8ykydntl1 foreign key (plan_id) references plans;
alter table subscriptions add constraint FKhro52ohfqfbay9774bev0qinr foreign key (user_id) references users on delete cascade;
alter table users add constraint FK4qu1gr772nnf6ve5af002rwya foreign key (role_id) references role;
alter table users_actors add constraint FK6g7k1w14vbb6rs6sfura29p0g foreign key (actor_id) references actors;
alter table users_actors add constraint FKmffc3v4ce9xfridbp3oenn2lk foreign key (user_id) references users;
alter table users_directors add constraint FK9yeirx8eip0563ibqpaq3ua06 foreign key (director_id) references directors;
alter table users_directors add constraint FKt16ii93flmtgoyq930q55s3hc foreign key (user_id) references users;
alter table users_genres add constraint FKqc52o4roeu9ub81u9xj35dfdc foreign key (genre_id) references genres;
alter table users_genres add constraint FK6jttrkotguvhmy7p9xmotflqq foreign key (user_id) references users;